/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniil Shmelev
-/
import Mathlib.Data.List.Perm.Basic
import Mathlib.Data.List.Perm.Lattice
import Mathlib.Data.Nat.Basic
import Mathlib.Data.Quot
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Abel
import Mathlib.Tactic.Positivity

/-!
# Rooted Trees

This file defines planar rooted trees together with the equivalence relation
generated by permuting the children at each vertex. The quotient by this
relation is the type of non-planar rooted trees.

The type `RootedTree` contains non-empty rooted trees. The empty tree used in
B-series indexing is adjoined separately as `TreeIndex.empty`.

## Main definitions

* `PTree` - non-empty planar rooted trees
* `PTree.Perm` - equivalence relation forgetting the planar embedding
* `RootedTree` - non-empty non-planar rooted trees
* `TreeIndex` - rooted trees with an adjoined empty tree

## References

* John C. Butcher, *Numerical Methods for Ordinary Differential Equations*
* Philippe Chartier, Ernst Hairer, Gilles Vilmart,
  *Algebraic Structures of B-series*
-/

namespace HopfAlgebras

/-- Non-empty planar rooted trees, where the list of children at each node is ordered. -/
inductive PTree : Type where
  | node : List PTree → PTree
deriving Repr

namespace PTree

/--
`t1.Perm t2` means that `t1` and `t2` differ only by permuting the children at
each vertex, recursively.
-/
inductive Perm : PTree → PTree → Prop where
  | node {ts1 ts2 ts1' : List PTree} :
      ts1.Perm ts1' →
      List.Forall₂ Perm ts1' ts2 →
      Perm (.node ts1) (.node ts2)

/-- The one-vertex planar rooted tree. -/
def bullet : PTree := .node []

/-- A two-vertex planar rooted tree. -/
def chain2 : PTree := .node [.bullet]

/-- A three-vertex planar chain. -/
def chain3 : PTree := .node [.chain2]

/-- A root with two bullet children. -/
def cherry : PTree := .node [.bullet, .bullet]

mutual

/-- The number of vertices of a planar rooted tree. -/
def order : PTree → Nat
  | .node ts => 1 + orderList ts

/-- The sum of the orders of a list of planar rooted trees. -/
def orderList : List PTree → Nat
  | [] => 0
  | t :: ts => order t + orderList ts

end

@[simp]
theorem order_node (ts : List PTree) : order (.node ts) = 1 + orderList ts :=
  rfl

@[simp]
theorem order_bullet : order bullet = 1 :=
  rfl

@[simp]
theorem order_chain2 : order chain2 = 2 :=
  rfl

@[simp]
theorem order_chain3 : order chain3 = 3 :=
  rfl

@[simp]
theorem order_cherry : order cherry = 3 :=
  rfl

@[simp]
theorem orderList_nil : orderList [] = 0 :=
  rfl

@[simp]
theorem orderList_cons (t : PTree) (ts : List PTree) :
    orderList (t :: ts) = order t + orderList ts :=
  rfl

@[simp]
theorem orderList_append (ts us : List PTree) :
    orderList (ts ++ us) = orderList ts + orderList us := by
  induction ts with
  | nil => simp
  | cons t ts ih =>
      simp [ih, Nat.add_assoc]

theorem order_pos : ∀ t : PTree, 0 < order t
  | .node ts => by
      simp only [order]
      omega

@[simp]
theorem orderList_reverse (ts : List PTree) :
    orderList ts.reverse = orderList ts := by
  induction ts with
  | nil => rfl
  | cons t ts ih =>
      rw [List.reverse_cons, orderList_append, ih, orderList_cons]
      simp [Nat.add_comm]

/-- The ordered list of subtrees at the root. -/
def children : PTree → List PTree
  | .node ts => ts

@[simp]
theorem children_node (ts : List PTree) : children (.node ts) = ts :=
  rfl

@[simp]
theorem node_children (t : PTree) : PTree.node t.children = t := by
  cases t
  rfl

theorem order_eq_one_add_orderList_children (t : PTree) :
    order t = 1 + orderList t.children := by
  cases t
  rfl

@[simp]
theorem orderList_eq_zero_iff : ∀ ts : List PTree, orderList ts = 0 ↔ ts = []
  | [] => by simp
  | t :: ts => by
      have ht := order_pos t
      constructor
      · intro h
        simp at h
        omega
      · intro h
        cases h

theorem order_eq_one_iff (t : PTree) : order t = 1 ↔ t = bullet := by
  constructor
  · cases t with
    | node ts =>
        intro h
        simp [bullet] at h ⊢
        exact h
  · intro h
    rw [h]
    simp

@[simp]
theorem orderList_eq_one_iff :
    ∀ ts : List PTree, orderList ts = 1 ↔ ts = [bullet]
  | [] => by simp
  | t :: ts => by
      constructor
      · intro h
        have htpos := order_pos t
        simp at h
        have ht : order t = 1 := by omega
        have hts : orderList ts = 0 := by omega
        rw [(order_eq_one_iff t).1 ht, (orderList_eq_zero_iff ts).1 hts]
      · intro h
        simp at h
        obtain ⟨ht, hts⟩ := h
        rw [ht, hts]
        simp

theorem order_eq_two_iff (t : PTree) : order t = 2 ↔ t = chain2 := by
  constructor
  · cases t with
    | node ts =>
        intro h
        simp [chain2] at h ⊢
        exact (orderList_eq_one_iff ts).1 (by omega)
  · intro h
    rw [h]
    simp

theorem orderList_eq_two_iff :
    ∀ ts : List PTree, orderList ts = 2 ↔ ts = [chain2] ∨ ts = [bullet, bullet]
  | [] => by simp
  | t :: ts => by
      constructor
      · intro h
        have htpos := order_pos t
        simp at h
        have ht : order t = 1 ∨ order t = 2 := by omega
        rcases ht with ht | ht
        · have hts : orderList ts = 1 := by omega
          right
          rw [(order_eq_one_iff t).1 ht, (orderList_eq_one_iff ts).1 hts]
        · have hts : orderList ts = 0 := by omega
          left
          rw [(order_eq_two_iff t).1 ht, (orderList_eq_zero_iff ts).1 hts]
      · intro h
        rcases h with h | h
        · rw [h]
          simp
        · rw [h]
          simp

theorem order_eq_three_iff (t : PTree) : order t = 3 ↔ t = chain3 ∨ t = cherry := by
  constructor
  · cases t with
    | node ts =>
        intro h
        simp [chain3, cherry] at h ⊢
        exact (orderList_eq_two_iff ts).1 (by omega)
  · intro h
    rcases h with h | h
    · rw [h]
      rfl
    · rw [h]
      rfl

mutual

/-- Butcher's tree factorial. -/
def treeFactorial : PTree → Nat
  | .node ts => order (.node ts) * treeFactorialList ts

/-- The product of tree factorials over a list of planar rooted trees. -/
def treeFactorialList : List PTree → Nat
  | [] => 1
  | t :: ts => treeFactorial t * treeFactorialList ts

end

@[simp]
theorem treeFactorial_node (ts : List PTree) :
    treeFactorial (.node ts) = order (.node ts) * treeFactorialList ts :=
  rfl

@[simp]
theorem treeFactorial_bullet : treeFactorial bullet = 1 :=
  rfl

@[simp]
theorem treeFactorial_chain2 : treeFactorial chain2 = 2 :=
  rfl

@[simp]
theorem treeFactorial_chain3 : treeFactorial chain3 = 6 :=
  rfl

@[simp]
theorem treeFactorial_cherry : treeFactorial cherry = 3 :=
  rfl

@[simp]
theorem treeFactorialList_nil : treeFactorialList [] = 1 :=
  rfl

@[simp]
theorem treeFactorialList_cons (t : PTree) (ts : List PTree) :
    treeFactorialList (t :: ts) = treeFactorial t * treeFactorialList ts :=
  rfl

mutual

theorem treeFactorial_pos : ∀ t : PTree, 0 < treeFactorial t
  | .node ts => by
      rw [treeFactorial_node]
      exact Nat.mul_pos (order_pos (.node ts)) (treeFactorialList_pos ts)

theorem treeFactorialList_pos : ∀ ts : List PTree, 0 < treeFactorialList ts
  | [] => by simp
  | t :: ts => by
      rw [treeFactorialList_cons]
      exact Nat.mul_pos (treeFactorial_pos t) (treeFactorialList_pos ts)

end

theorem treeFactorial_ne_zero (t : PTree) : treeFactorial t ≠ 0 :=
  Nat.ne_of_gt (treeFactorial_pos t)

theorem treeFactorialList_ne_zero (ts : List PTree) : treeFactorialList ts ≠ 0 :=
  Nat.ne_of_gt (treeFactorialList_pos ts)

@[simp]
theorem treeFactorialList_append (ts us : List PTree) :
    treeFactorialList (ts ++ us) = treeFactorialList ts * treeFactorialList us := by
  induction ts with
  | nil => simp
  | cons t ts ih =>
      simp [ih, Nat.mul_assoc]

/-- Attach an ordered forest as the first children of the root of a planar tree. -/
def butcherProduct (ts : List PTree) : PTree → PTree
  | .node us => .node (ts ++ us)

@[simp]
theorem butcherProduct_node (ts us : List PTree) :
    butcherProduct ts (.node us) = .node (ts ++ us) :=
  rfl

@[simp]
theorem butcherProduct_nil (t : PTree) : butcherProduct [] t = t := by
  cases t
  simp [butcherProduct]

@[simp]
theorem butcherProduct_bullet (ts : List PTree) :
    butcherProduct ts bullet = .node ts := by
  simp [butcherProduct, bullet]

@[simp]
theorem order_butcherProduct (ts : List PTree) (t : PTree) :
    order (butcherProduct ts t) = orderList ts + order t := by
  cases t with
  | node us =>
      simp [butcherProduct, order]
      omega

@[simp]
theorem butcherProduct_assoc (ts us : List PTree) (t : PTree) :
    butcherProduct ts (butcherProduct us t) = butcherProduct (ts ++ us) t := by
  cases t
  simp [butcherProduct, List.append_assoc]

theorem treeFactorial_butcherProduct (ts us : List PTree) :
    treeFactorial (butcherProduct ts (.node us)) =
      (orderList ts + order (.node us)) *
        (treeFactorialList ts * treeFactorialList us) := by
  change
    (1 + orderList (ts ++ us)) * treeFactorialList (ts ++ us) =
      (orderList ts + (1 + orderList us)) *
        (treeFactorialList ts * treeFactorialList us)
  rw [orderList_append, treeFactorialList_append]
  have horder : 1 + (orderList ts + orderList us) = orderList ts + (1 + orderList us) := by
    omega
  rw [horder]

/--
If a relation `R` holds elementwise between `l1` and `l2`, then after
permuting `l2` we can permute `l1` so that `R` still holds elementwise.
-/
lemma forall2_perm_right {α β : Type _} {R : α → β → Prop} {l2 l3 : List β}
    (hp : l2.Perm l3) :
    ∀ {l1 : List α}, List.Forall₂ R l1 l2 →
      ∃ l1', l1.Perm l1' ∧ List.Forall₂ R l1' l3 := by
  induction hp with
  | nil =>
      intro l1 hf
      cases hf
      exact ⟨[], .nil, .nil⟩
  | cons _ _ ih =>
      intro l1 hf
      cases hf with
      | cons ha hf =>
          obtain ⟨l1', hp', hf'⟩ := ih hf
          exact ⟨_ :: l1', .cons _ hp', .cons ha hf'⟩
  | swap _ _ _ =>
      intro l1 hf
      cases hf with
      | cons ha hf =>
          cases hf with
          | cons hb hf =>
              exact ⟨_ :: _ :: _, .swap _ _ _, .cons hb (.cons ha hf)⟩
  | trans _ _ ih12 ih23 =>
      intro l1 hf
      obtain ⟨l1', hp', hf'⟩ := ih12 hf
      obtain ⟨l1'', hp'', hf''⟩ := ih23 hf'
      exact ⟨l1'', hp'.trans hp'', hf''⟩

/-- Lists related elementwise up to a permutation of the left list. -/
def ListRelPerm {α β : Type _} (R : α → β → Prop) (xs : List α) (ys : List β) : Prop :=
  ∃ xs', xs.Perm xs' ∧ List.Forall₂ R xs' ys

namespace ListRelPerm

private theorem forall₂_map {α β γ δ : Type _} {R : α → β → Prop}
    {S : γ → δ → Prop} {f : α → γ} {g : β → δ}
    (hS : ∀ {x y}, R x y → S (f x) (g y)) :
    ∀ {xs : List α} {ys : List β}, List.Forall₂ R xs ys →
      List.Forall₂ S (xs.map f) (ys.map g)
  | _, _, .nil => .nil
  | _, _, .cons h hs => .cons (hS h) (forall₂_map (f := f) (g := g) hS hs)

private theorem forall₂_append {α β : Type _} {R : α → β → Prop} :
    ∀ {xs₁ : List α} {ys₁ : List β}, List.Forall₂ R xs₁ ys₁ →
      ∀ {xs₂ : List α} {ys₂ : List β}, List.Forall₂ R xs₂ ys₂ →
        List.Forall₂ R (xs₁ ++ xs₂) (ys₁ ++ ys₂)
  | _, _, .nil, _, _, h₂ => h₂
  | _, _, .cons h hs, _, _, h₂ => .cons h (forall₂_append hs h₂)

private theorem forall₂_trans {α : Type _} {R : α → α → Prop}
    (htrans : ∀ {x y z : α}, R x y → R y z → R x z) :
    ∀ {xs ys zs : List α}, List.Forall₂ R xs ys →
      List.Forall₂ R ys zs → List.Forall₂ R xs zs
  | [], [], [], .nil, .nil => .nil
  | _ :: xs, _ :: ys, _ :: zs, .cons hxy hxs, .cons hyz hys =>
      .cons (htrans hxy hyz) (@forall₂_trans α R htrans xs ys zs hxs hys)

private theorem perm_flatMap_same {α β : Type _} (f : α → List β) :
    ∀ {xs ys : List α}, xs.Perm ys → (xs.flatMap f).Perm (ys.flatMap f)
  | _, _, .nil => .nil
  | _, _, .cons a h => by
      simpa [List.flatMap_cons] using List.Perm.append_left (f a) (perm_flatMap_same f h)
  | _, _, .swap a b xs => by
      have h : (f b ++ f a).Perm (f a ++ f b) := List.Perm.symm List.perm_append_comm
      simpa [List.flatMap_cons, List.append_assoc] using List.Perm.append_right (xs.flatMap f) h
  | _, _, .trans h₁ h₂ => (perm_flatMap_same f h₁).trans (perm_flatMap_same f h₂)

theorem of_forall₂ {α β : Type _} {R : α → β → Prop} {xs : List α} {ys : List β}
    (h : List.Forall₂ R xs ys) : ListRelPerm R xs ys :=
  ⟨xs, List.Perm.refl xs, h⟩

theorem perm_left {α β : Type _} {R : α → β → Prop} {xs xs' : List α} {ys : List β}
    (hp : xs.Perm xs') (h : ListRelPerm R xs' ys) : ListRelPerm R xs ys := by
  rcases h with ⟨xs'', hp', hrel⟩
  exact ⟨xs'', hp.trans hp', hrel⟩

theorem of_perm_left_forall₂ {α β : Type _} {R : α → β → Prop}
    {xs xs' : List α} {ys : List β} (hp : xs.Perm xs')
    (h : List.Forall₂ R xs' ys) : ListRelPerm R xs ys :=
  ⟨xs', hp, h⟩

theorem map {α β γ δ : Type _} {R : α → β → Prop} {S : γ → δ → Prop}
    {xs : List α} {ys : List β} {f : α → γ} {g : β → δ}
    (hS : ∀ {x y}, R x y → S (f x) (g y))
    (h : ListRelPerm R xs ys) : ListRelPerm S (xs.map f) (ys.map g) := by
  rcases h with ⟨xs', hp, hrel⟩
  exact ⟨xs'.map f, hp.map f, forall₂_map (f := f) (g := g) hS hrel⟩

theorem cons {α β : Type _} {R : α → β → Prop} {x : α} {y : β}
    {xs : List α} {ys : List β} (hxy : R x y) (h : ListRelPerm R xs ys) :
    ListRelPerm R (x :: xs) (y :: ys) := by
  rcases h with ⟨xs', hp, hrel⟩
  exact ⟨x :: xs', .cons x hp, .cons hxy hrel⟩

theorem refl {α : Type _} {R : α → α → Prop} (hrefl : ∀ x, R x x) :
    ∀ xs : List α, ListRelPerm R xs xs
  | [] => of_forall₂ .nil
  | x :: xs => cons (hrefl x) (refl hrefl xs)

theorem append {α β : Type _} {R : α → β → Prop}
    {xs₁ xs₂ : List α} {ys₁ ys₂ : List β}
    (h₁ : ListRelPerm R xs₁ ys₁) (h₂ : ListRelPerm R xs₂ ys₂) :
    ListRelPerm R (xs₁ ++ xs₂) (ys₁ ++ ys₂) := by
  rcases h₁ with ⟨xs₁', hp₁, hrel₁⟩
  rcases h₂ with ⟨xs₂', hp₂, hrel₂⟩
  exact ⟨xs₁' ++ xs₂', hp₁.append hp₂, forall₂_append hrel₁ hrel₂⟩

theorem trans {α : Type _} {R : α → α → Prop}
    (htrans : ∀ {x y z : α}, R x y → R y z → R x z)
    {xs ys zs : List α} (hxy : ListRelPerm R xs ys)
    (hyz : ListRelPerm R ys zs) : ListRelPerm R xs zs := by
  rcases hxy with ⟨xs', hpxs, hrelxy⟩
  rcases hyz with ⟨ys', hpys, hrelyz⟩
  obtain ⟨xs'', hpxs', hrelxy'⟩ :=
    PTree.forall2_perm_right (R := R) hpys hrelxy
  exact ⟨xs'', hpxs.trans hpxs',
    @forall₂_trans α R htrans xs'' ys' zs hrelxy' hrelyz⟩

private theorem eq_of_forall₂_eq {α : Type _} :
    ∀ {xs ys : List α}, List.Forall₂ (fun x y => x = y) xs ys → xs = ys
  | [], [], .nil => rfl
  | _ :: _, _ :: _, .cons h hs => by
      simp [h, eq_of_forall₂_eq hs]

theorem perm_of_eq {α : Type _} {xs ys : List α}
    (h : ListRelPerm (fun x y => x = y) xs ys) : xs.Perm ys := by
  rcases h with ⟨xs', hp, hrel⟩
  rw [← eq_of_forall₂_eq hrel]
  exact hp

theorem map_eq_perm {α β γ : Type _} {R : α → β → Prop}
    {xs : List α} {ys : List β} {f : α → γ} {g : β → γ}
    (hfg : ∀ {x y}, R x y → f x = g y)
    (h : ListRelPerm R xs ys) : (xs.map f).Perm (ys.map g) :=
  perm_of_eq (map (S := fun x y => x = y) hfg h)

private theorem flatMap_of_forall₂ {α β γ δ : Type _}
    {R : α → β → Prop} {S : γ → δ → Prop}
    {f : α → List γ} {g : β → List δ}
    (hfg : ∀ {x y}, R x y → ListRelPerm S (f x) (g y)) :
    ∀ {xs : List α} {ys : List β}, List.Forall₂ R xs ys →
      ListRelPerm S (xs.flatMap f) (ys.flatMap g)
  | _, _, .nil => of_forall₂ .nil
  | _, _, .cons h hs => by
      simpa [List.flatMap_cons] using
        append (hfg h) (flatMap_of_forall₂ (f := f) (g := g) hfg hs)

theorem flatMap {α β γ δ : Type _}
    {R : α → β → Prop} {S : γ → δ → Prop}
    {xs : List α} {ys : List β} {f : α → List γ} {g : β → List δ}
    (hfg : ∀ {x y}, R x y → ListRelPerm S (f x) (g y))
    (h : ListRelPerm R xs ys) : ListRelPerm S (xs.flatMap f) (ys.flatMap g) := by
  rcases h with ⟨xs', hp, hrel⟩
  exact perm_left (perm_flatMap_same f hp) (flatMap_of_forall₂ (f := f) (g := g) hfg hrel)

end ListRelPerm

/-- `orderList` is invariant under permuting a list of planar trees. -/
theorem orderList_perm {ts1 ts2 : List PTree} (h : ts1.Perm ts2) :
    orderList ts1 = orderList ts2 := by
  induction h with
  | nil => rfl
  | cons _ _ ih => simp [ih]
  | swap _ _ _ => simp [Nat.add_left_comm]
  | trans _ _ ih12 ih23 => exact ih12.trans ih23

/-- `treeFactorialList` is invariant under permuting a list of planar trees. -/
theorem treeFactorialList_perm {ts1 ts2 : List PTree} (h : ts1.Perm ts2) :
    treeFactorialList ts1 = treeFactorialList ts2 := by
  induction h with
  | nil => rfl
  | cons _ _ ih => simp [ih]
  | swap _ _ _ => simp [Nat.mul_left_comm]
  | trans _ _ ih12 ih23 => exact ih12.trans ih23

mutual

/-- `PTree.Perm` is reflexive. -/
theorem Perm.refl : ∀ t : PTree, Perm t t
  | .node ts => .node (List.Perm.refl ts) (permForall2_refl ts)

/-- Elementwise reflexivity for `PTree.Perm`. -/
theorem permForall2_refl : ∀ ts : List PTree, List.Forall₂ Perm ts ts
  | [] => .nil
  | t :: ts => .cons (Perm.refl t) (permForall2_refl ts)

end

mutual

/-- Elementwise symmetry for `PTree.Perm`. -/
theorem permForall2_symm :
    ∀ {ts1 ts2 : List PTree},
      List.Forall₂ Perm ts1 ts2 → List.Forall₂ Perm ts2 ts1
  | _, _, .nil => .nil
  | _, _, .cons h hs => .cons (Perm.symm h) (permForall2_symm hs)

/-- `PTree.Perm` is symmetric. -/
theorem Perm.symm : ∀ {t1 t2 : PTree}, Perm t1 t2 → Perm t2 t1
  | _, _, .node hp hf => by
      obtain ⟨ts2', hp2, hf2⟩ :=
        forall2_perm_right (R := Perm) hp.symm (permForall2_symm hf)
      exact .node hp2 hf2

end

mutual

/-- Elementwise transitivity for `PTree.Perm`. -/
theorem permForall2_trans :
    ∀ {ts1 ts2 ts3 : List PTree},
      List.Forall₂ Perm ts1 ts2 →
      List.Forall₂ Perm ts2 ts3 →
      List.Forall₂ Perm ts1 ts3
  | _, _, _, .nil, .nil => .nil
  | _, _, _, .cons h12 hs12, .cons h23 hs23 =>
      .cons (Perm.trans h12 h23) (permForall2_trans hs12 hs23)

/-- `PTree.Perm` is transitive. -/
theorem Perm.trans : ∀ {t1 t2 t3 : PTree}, Perm t1 t2 → Perm t2 t3 → Perm t1 t3
  | _, _, _, .node hp12 hf12, .node hp23 hf23 => by
      obtain ⟨ts, hp, hf⟩ := forall2_perm_right (R := Perm) hp23 hf12
      exact .node (hp12.trans hp) (permForall2_trans hf hf23)

end

mutual

/-- `PTree.Perm` preserves the number of vertices. -/
theorem Perm.order_eq : ∀ {t1 t2 : PTree}, Perm t1 t2 → order t1 = order t2
  | _, _, .node hp hf => by
      simp [orderList_perm hp, orderList_eq_of_forall2 hf]

/-- Elementwise `PTree.Perm` preserves the total number of vertices. -/
theorem orderList_eq_of_forall2 :
    ∀ {ts1 ts2 : List PTree}, List.Forall₂ Perm ts1 ts2 → orderList ts1 = orderList ts2
  | _, _, .nil => rfl
  | _, _, .cons h hs => by
      simp [Perm.order_eq h, orderList_eq_of_forall2 hs]

end

mutual

/-- `PTree.Perm` preserves Butcher's tree factorial. -/
theorem Perm.treeFactorial_eq :
    ∀ {t1 t2 : PTree}, Perm t1 t2 → treeFactorial t1 = treeFactorial t2
  | _, _, .node hp hf => by
      simp [
        orderList_perm hp,
        orderList_eq_of_forall2 hf,
        treeFactorialList_perm hp,
        treeFactorialList_eq_of_forall2 hf
      ]

/-- Elementwise `PTree.Perm` preserves the product of tree factorials. -/
theorem treeFactorialList_eq_of_forall2 :
    ∀ {ts1 ts2 : List PTree},
      List.Forall₂ Perm ts1 ts2 → treeFactorialList ts1 = treeFactorialList ts2
  | _, _, .nil => rfl
  | _, _, .cons h hs => by
      simp [Perm.treeFactorial_eq h, treeFactorialList_eq_of_forall2 hs]

end

instance : Setoid PTree where
  r := Perm
  iseqv := ⟨Perm.refl, Perm.symm, Perm.trans⟩

/-- If the children are pairwise permutation-equivalent, then the nodes are too. -/
theorem perm_node_of_forall2 {ts1 ts2 : List PTree} (h : List.Forall₂ Perm ts1 ts2) :
    Perm (.node ts1) (.node ts2) :=
  .node (List.Perm.refl _) h

end PTree

/-- Non-empty non-planar rooted trees are planar rooted trees modulo `PTree.Perm`. -/
abbrev RootedTree : Type := Quotient (inferInstance : Setoid PTree)

namespace RootedTree

/-- The quotient map from planar rooted trees to non-planar rooted trees. -/
def ofPTree (t : PTree) : RootedTree :=
  Quotient.mk _ t

theorem ofPTree_eq_iff {t u : PTree} :
    ofPTree t = ofPTree u ↔ PTree.Perm t u := by
  constructor
  · intro h
    exact Quotient.exact h
  · intro h
    exact Quotient.sound h

/-- The one-vertex non-planar rooted tree. -/
def bullet : RootedTree :=
  ofPTree PTree.bullet

/-- The two-vertex non-planar rooted tree. -/
def chain2 : RootedTree :=
  ofPTree PTree.chain2

/-- The three-vertex non-planar chain. -/
def chain3 : RootedTree :=
  ofPTree PTree.chain3

/-- A root with two bullet children. -/
def cherry : RootedTree :=
  ofPTree PTree.cherry

/-- The number of vertices of a non-planar rooted tree. -/
def order : RootedTree → Nat :=
  Quotient.lift PTree.order (fun _ _ h => PTree.Perm.order_eq h)

/-- Predicate for non-empty rooted trees of a fixed order. -/
def IsOfOrder (τ : RootedTree) (n : Nat) : Prop :=
  order τ = n

@[simp]
theorem order_ofPTree (t : PTree) : order (ofPTree t) = PTree.order t :=
  rfl

@[simp]
theorem order_bullet : order bullet = 1 :=
  rfl

@[simp]
theorem order_chain2 : order chain2 = 2 :=
  rfl

@[simp]
theorem order_chain3 : order chain3 = 3 :=
  rfl

@[simp]
theorem order_cherry : order cherry = 3 :=
  rfl

theorem order_pos (τ : RootedTree) : 0 < order τ :=
  Quotient.inductionOn τ PTree.order_pos

theorem order_eq_one_iff (τ : RootedTree) : order τ = 1 ↔ τ = bullet := by
  refine Quotient.inductionOn τ ?_
  intro t
  constructor
  · intro h
    exact congrArg RootedTree.ofPTree ((PTree.order_eq_one_iff t).1 h)
  · intro h
    rw [h]
    simp

theorem order_eq_two_iff (τ : RootedTree) : order τ = 2 ↔ τ = chain2 := by
  refine Quotient.inductionOn τ ?_
  intro t
  constructor
  · intro h
    exact congrArg RootedTree.ofPTree ((PTree.order_eq_two_iff t).1 h)
  · intro h
    rw [h]
    simp

theorem order_eq_three_iff (τ : RootedTree) : order τ = 3 ↔ τ = chain3 ∨ τ = cherry := by
  refine Quotient.inductionOn τ ?_
  intro t
  constructor
  · intro h
    rcases (PTree.order_eq_three_iff t).1 h with h | h
    · left
      exact congrArg RootedTree.ofPTree h
    · right
      exact congrArg RootedTree.ofPTree h
  · intro h
    rcases h with h | h
    · rw [h]
      simp
    · rw [h]
      simp

/-- Butcher's tree factorial for non-planar rooted trees. -/
def treeFactorial : RootedTree → Nat :=
  Quotient.lift PTree.treeFactorial (fun _ _ h => PTree.Perm.treeFactorial_eq h)

@[simp]
theorem treeFactorial_ofPTree (t : PTree) :
    treeFactorial (ofPTree t) = PTree.treeFactorial t :=
  rfl

@[simp]
theorem ofPTree_out (τ : RootedTree) : ofPTree (Quotient.out τ) = τ :=
  Quotient.out_eq τ

theorem out_perm_ofPTree (t : PTree) :
    PTree.Perm (Quotient.out (ofPTree t)) t :=
  Quotient.exact (ofPTree_out (ofPTree t))

theorem map_ofPTree_eq_of_forall₂_perm :
    ∀ {ts us : List PTree}, List.Forall₂ PTree.Perm ts us →
      ts.map ofPTree = us.map ofPTree
  | _, _, .nil => rfl
  | _, _, .cons h hs => by
      simp [
        show ofPTree _ = ofPTree _ from ofPTree_eq_iff.2 h,
        map_ofPTree_eq_of_forall₂_perm hs
      ]

@[simp]
theorem treeFactorial_bullet : treeFactorial bullet = 1 :=
  rfl

@[simp]
theorem treeFactorial_chain2 : treeFactorial chain2 = 2 :=
  rfl

@[simp]
theorem treeFactorial_chain3 : treeFactorial chain3 = 6 :=
  rfl

@[simp]
theorem treeFactorial_cherry : treeFactorial cherry = 3 :=
  rfl

theorem treeFactorial_pos (τ : RootedTree) : 0 < treeFactorial τ := by
  refine Quotient.inductionOn τ ?_
  intro t
  exact PTree.treeFactorial_pos t

theorem treeFactorial_ne_zero (τ : RootedTree) : treeFactorial τ ≠ 0 :=
  Nat.ne_of_gt (treeFactorial_pos τ)

end RootedTree

/-- Rooted trees with an adjoined empty tree, as used for B-series coefficients. -/
inductive TreeIndex : Type where
  | empty : TreeIndex
  | tree : RootedTree → TreeIndex

namespace TreeIndex

/-- The one-vertex tree as a B-series index. -/
def bullet : TreeIndex :=
  .tree RootedTree.bullet

/-- The two-vertex tree as a B-series index. -/
def chain2 : TreeIndex :=
  .tree RootedTree.chain2

/-- The three-vertex chain as a B-series index. -/
def chain3 : TreeIndex :=
  .tree RootedTree.chain3

/-- The cherry tree as a B-series index. -/
def cherry : TreeIndex :=
  .tree RootedTree.cherry

/-- The order of a B-series tree index. -/
def order : TreeIndex → Nat
  | .empty => 0
  | .tree τ => RootedTree.order τ

/-- Predicate for B-series tree indices of a fixed order. -/
def IsOfOrder (τ : TreeIndex) (n : Nat) : Prop :=
  order τ = n

/-- Butcher's tree factorial for B-series tree indices. -/
def treeFactorial : TreeIndex → Nat
  | .empty => 1
  | .tree τ => RootedTree.treeFactorial τ

@[simp]
theorem order_empty : order .empty = 0 :=
  rfl

@[simp]
theorem order_tree (τ : RootedTree) : order (.tree τ) = RootedTree.order τ :=
  rfl

@[simp]
theorem order_bullet : order bullet = 1 :=
  rfl

@[simp]
theorem order_chain2 : order chain2 = 2 :=
  rfl

@[simp]
theorem order_chain3 : order chain3 = 3 :=
  rfl

@[simp]
theorem order_cherry : order cherry = 3 :=
  rfl

@[simp]
theorem order_eq_zero_iff : ∀ τ : TreeIndex, order τ = 0 ↔ τ = .empty
  | .empty => by simp
  | .tree τ => by
      constructor
      · intro h
        exact False.elim ((Nat.ne_of_gt (RootedTree.order_pos τ)) h)
      · intro h
        cases h

theorem order_pos_iff_ne_empty (τ : TreeIndex) : 0 < order τ ↔ τ ≠ .empty := by
  constructor
  · intro h hτ
    rw [hτ] at h
    simp at h
  · intro h
    have horder : order τ ≠ 0 := by
      intro hzero
      exact h ((order_eq_zero_iff τ).1 hzero)
    omega

@[simp]
theorem order_eq_one_iff : ∀ τ : TreeIndex, order τ = 1 ↔ τ = bullet
  | .empty => by
      constructor
      · intro h
        cases h
      · intro h
        cases h
  | .tree τ => by
      constructor
      · intro h
        exact congrArg TreeIndex.tree ((RootedTree.order_eq_one_iff τ).1 h)
      · intro h
        rw [h]
        simp [bullet]

theorem order_eq_two_iff : ∀ τ : TreeIndex, order τ = 2 ↔ τ = chain2
  | .empty => by
      constructor
      · intro h
        cases h
      · intro h
        cases h
  | .tree τ => by
      constructor
      · intro h
        exact congrArg TreeIndex.tree ((RootedTree.order_eq_two_iff τ).1 h)
      · intro h
        rw [h]
        simp [chain2]

theorem order_eq_three_iff :
    ∀ τ : TreeIndex, order τ = 3 ↔ τ = chain3 ∨ τ = cherry
  | .empty => by
      constructor
      · intro h
        cases h
      · intro h
        rcases h with h | h <;> cases h
  | .tree τ => by
      constructor
      · intro h
        rcases (RootedTree.order_eq_three_iff τ).1 h with h | h
        · left
          exact congrArg TreeIndex.tree h
        · right
          exact congrArg TreeIndex.tree h
      · intro h
        rcases h with h | h
        · rw [h]
          simp [chain3]
        · rw [h]
          simp [cherry]

@[simp]
theorem treeFactorial_empty : treeFactorial .empty = 1 :=
  rfl

@[simp]
theorem treeFactorial_tree (τ : RootedTree) :
    treeFactorial (.tree τ) = RootedTree.treeFactorial τ :=
  rfl

@[simp]
theorem treeFactorial_bullet : treeFactorial bullet = 1 :=
  rfl

@[simp]
theorem treeFactorial_chain2 : treeFactorial chain2 = 2 :=
  rfl

@[simp]
theorem treeFactorial_chain3 : treeFactorial chain3 = 6 :=
  rfl

@[simp]
theorem treeFactorial_cherry : treeFactorial cherry = 3 :=
  rfl

theorem treeFactorial_pos : ∀ τ : TreeIndex, 0 < treeFactorial τ
  | .empty => by simp
  | .tree τ => RootedTree.treeFactorial_pos τ

theorem treeFactorial_ne_zero (τ : TreeIndex) : treeFactorial τ ≠ 0 :=
  Nat.ne_of_gt (treeFactorial_pos τ)

end TreeIndex

end HopfAlgebras
